openapi: 3.0.1
info:
  title: API
  description: Diseño de apis para aplicacion movil
  version: v1

paths:
  /api/cooperativa/lista-cooperativa:
    get:
      tags:
        - cooperativa
      summary: Lista de cooperativas disponibles
      description: Devuelve el listado de todas las cooperativas disponibles
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cadenaCooperativasResponse"
  
  /api/cooperativa/verificar-codigo:
    post:
      tags:
        - cooperativa
      summary: Verifica código de cooperativa
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cadenaCooperativaCodigoRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/cadenaCooperativaCodigoResponse"
        
  /api/cuenta/autenticar:
    post:
      tags:
        - cuenta
      summary: Autenticar usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cadenaAutenticarRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cadenaAutenticarResponse"

  /api/cuenta/registro:
    post:
      tags:
        - cuenta
      summary: Registrar usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cadenaRegistroRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cadenaRegistroResponse"

  /api/cuenta/recuperar-password:
    post:
      tags:
        - cuenta
      summary: Envío de email para recuperación de contraseña
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cadenaRecuperarpasswordRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cadenaRecuperarpasswordResponse"

  /api/cuenta/reiniciar-password:
    post:
      tags:
        - cuenta
      summary: Reiniciar contraseña
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cadenaReiniciarpasswordRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cadenaReiniciarpasswordResponse"

  /api/cuenta/cambiar-password:
    post:
      tags:
        - cuenta
      summary: Cambio de contraseña
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cadenaCambiarpasswordRequest"
      responses:
        200:
          description: Success
  
  /api/cuenta/status-token:
    post:
      tags:
        - cuenta
      summary: Refresh access token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cadenaStatustokenRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cadenaStatustokenResponse"
                

components:
  schemas:
    cadenaCooperativasResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/listaCooperativas"
          nullable: true
      additionalProperties: false
    
    listaCooperativas:
      type: object
      properties:
        codigo:
          type: string
        nombre:
          type: string

    cadenaCooperativaCodigoRequest:
      type:  object
      required:
        - codigo
        - codigoCooperativa
      properties:
        codigo:
          type: string
        codigoCooperativa:
          type: number
      additionalProperties: false

    cadenaCooperativaCodigoResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              verificado:
                type: boolean
              mensaje:
                type: string
      additionalProperties: false

    cadenaAutenticarRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
        password2:
          type: string          
      additionalProperties: false

    cadenaAutenticarResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              usuario:
                type: string
              correo:
                type: string
              isVerified:
                type: boolean
              jwToken:
                type: string
              refreshToken:
                type: string
      additionalProperties: false

    cadenaRegistroRequest:
      type: object
      required:
        - nombre
        - apellido
        - correo
        - fechaNacimiento
        - cooperativa
        - password
        - confirmarPassword
      properties:
        nombre:
          type: string
        apellido:
          type: string
        correo:
          type: string
        telefono:
          type: string
        fechaNacimiento:
          type: string
        cooperativa:
          type: number
        password:
          type: string
        confirmarPassword:
          type: string
      additionalProperties: false

    cadenaRegistroResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
        data:
          type: string
      additionalProperties: false

    cadenaRecuperarpasswordRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
      additionalProperties: false

    cadenaRecuperarpasswordResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
        data:
          type: string
      additionalProperties: false         

    cadenaReiniciarpasswordRequest:
      type: object
      required:
        - oldPassword
        - newPassword
        - confirmPassword
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
        confirmPassword:
          type: string
      additionalProperties: false
    
    cadenaReiniciarpasswordResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
        data:
          type: string
      additionalProperties: false

    cadenaCambiarpasswordRequest:
      type: object
      properties:
        password:
          type: string
        confirmPassword:
          type: string
        email:
          type: string
        token:
          type: string

    cadenaStatustokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
        accessToken:
          type: string
      additionalProperties: false

    cadenaStatustokenResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              usuario:
                type: string
              correo:
                type: string
              isVerified:
                type: boolean
              jwToken:
                type: string
              refreshToken:
                type: string
      additionalProperties: false     