openapi: 3.0.1
info:
  title: API
  description: Diseño de apis para aplicacion movil
  version: v1

paths:
  /api/cooperativa/listacoope:
    get:
      tags:
        - cooperativa
      summary: Lista de cooperativas disponibles
      description: Devuelve el listado de todas las cooperativas disponibles
      responses:
        200:
          description: Success
          content:
            aplication/json:
              schema:
                $ref: "#/components/schemas/cadenaCooperativasResponse"

components:
  schemas:
    cadenaCooperativasResponse:
      type: object
      properties:
        resultado:
          type: boolean
        mensaje:
          type: string
          nullable: true
        data:
          type: array
          items:
            $ref: "#/components/schemas/listaCooperativas"
          nullable: true
      additionalProperties: false
    
    listaCooperativas:
      type: object
      properties:
        codigo:
          type: string
          nullable: false
        nombre:
          type: string
          nullable: false
